include ${GYROEP_ROOT}/shared/install/make.inc.${GYROEP_PLATFORM}

all:
	cd gyro2gkv ; make "OPT=${OPT}"
	cd fieldline ; make "OPT=${OPT}"

clean:
	cd gyro2gkv ; make clean
	cd fieldline ; make clean

